name: test
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.x"
        - name: Install package
          run: |
            python -m pip install --upgrade pip
            pip install .
        - name: Download filters
          run: |
            xspect download-filters
        - name: Test with pytest
          run: |
            pip install pytest pytest-cov
            pytest --cov
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3
          env:
            CODECOV_TOKEN: $({ secrets.CODECOV_TOKEN 3}
        
        